### ISSUE TITLE
Error while trying to run the model

### ISSUE THREAD

**Issue by thomasdqr** [esnya/rvc-eval#2]
I tried running the default command using a custom model and got this error :
`2023-09-28 19:56:14 | INFO | fairseq.tasks.hubert_pretraining | current directory is C:\Users\xxx\Documents\RVC\rvc-eval
2023-09-28 19:56:14 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-09-28 19:56:14 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
gin_channels: 256 self.spk_embed_dim: 109
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\Documents\RVC\rvc-eval\rvc_eval\cli.py", line 149, in <module>
    main(args)
  File "C:\Users\xxx\Documents\RVC\rvc-eval\rvc_eval\cli.py", line 25, in main
    net_g, sampling_ratio = load_net_g(args.model, is_half, device)
  File "C:\Users\xxx\Documents\RVC\rvc-eval\rvc_eval\model.py", line 22, in load_net_g
    net_g.load_state_dict(cpt["weight"], strict=False)
  File "C:\Users\xxx\.virtualenvs\rvc-eval-pzEv9evV\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid:
        size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256]).`

Do you have any idea why this is not working ?

**Comment by artificialnouveau** [comment]
Sorry I also get this error, please try to use the stable-v1 branch

**Comment by thomasdqr** [comment]
I only see one branch on the repo 🤔 What am I doing wrong ?

**Comment by artificialnouveau** [comment]
I've updated my main branch: https://github.com/artificialnouveau/rvc-eval . Could you check if it solves the issues you are facing: @thomasdqr

**Comment by esnya** [comment]
Sorry I haven't spent more time on this product. 

@artificialnouveau It's looks like great work. Could you make as Pull Request?

I'm watching for a VITS implementation on transformers. But it is moving slower than I expected...

**Comment by esnya** [comment]
#3 は同じload_net_g系の報告としてこのissueへ集約します。再開する場合はcheckpoint versionと256/768次元のdispatch、fixtureをこのissueで扱います。
